.TH "ROWS PRINT" "1" "2020-12-16" "-0.4.2-dev-eaa8b1ac-" "rows print Manual"
.SH NAME
rows\-print \- Print a table
.SH SYNOPSIS
.B rows print
[OPTIONS] SOURCE
.SH DESCRIPTION
Print a table
.SH OPTIONS
.TP
\fB\-\-input\-encoding\fP TEXT
.PP
.TP
\fB\-\-output\-encoding\fP TEXT
.PP
.TP
\fB\-\-input\-locale\fP TEXT
.PP
.TP
\fB\-i,\fP \-\-input\-option TEXT
Custom (import) plugin key=value custom option (can be specified multiple times)
.TP
\fB\-\-output\-locale\fP TEXT
.PP
.TP
\fB\-\-frame\-style\fP TEXT
Options: ascii, single, double, none
.TP
\fB\-\-table\-index\fP INTEGER
.PP
.TP
\fB\-\-verify\-ssl\fP BOOLEAN
.PP
.TP
\fB\-\-fields\fP TEXT
A comma-separated list of fields to import
.TP
\fB\-\-fields\-exclude\fP TEXT
A comma-separated list of fields to exclude
.TP
\fB\-\-order\-by\fP TEXT
.PP
.TP
\fB\-q,\fP \-\-quiet
.PP
