.TH "ROWS JOIN" "1" "2020-12-16" "-0.4.2-dev-eaa8b1ac-" "rows join Manual"
.SH NAME
rows\-join \- Join tables from `source` URIs using `key(s)`...
.SH SYNOPSIS
.B rows join
[OPTIONS] KEYS SOURCES... DESTINATION
.SH DESCRIPTION
Join tables from `source` URIs using `key(s)` to group rows and save into `destination`
.SH OPTIONS
.TP
\fB\-\-input\-encoding\fP TEXT
.PP
.TP
\fB\-\-output\-encoding\fP TEXT
.PP
.TP
\fB\-\-input\-locale\fP TEXT
.PP
.TP
\fB\-\-output\-locale\fP TEXT
.PP
.TP
\fB\-\-verify\-ssl\fP BOOLEAN
.PP
.TP
\fB\-\-order\-by\fP TEXT
.PP
.TP
\fB\-\-fields\fP TEXT
A comma-separated list of fields to export
.TP
\fB\-\-fields\-exclude\fP TEXT
A comma-separated list of fields to exclude when exporting
