.TH "ROWS PGIMPORT" "1" "2020-12-16" "-0.4.2-dev-eaa8b1ac-" "rows pgimport Manual"
.SH NAME
rows\-pgimport \- Import a CSV file into a PostgreSQL table
.SH SYNOPSIS
.B rows pgimport
[OPTIONS] SOURCE DATABASE_URI TABLE_NAME
.SH DESCRIPTION
Import a CSV file into a PostgreSQL table
.SH OPTIONS
.TP
\fB\-\-input\-encoding\fP TEXT
.PP
.TP
\fB\-\-no\-create\-table\fP
.PP
.TP
\fB\-\-dialect\fP TEXT
.PP
.TP
\fB\-\-schema\fP TEXT
.PP
.TP
\fB\-\-unlogged\fP
.PP
