.TH "ROWS PDF-TO-TEXT" "1" "2020-12-16" "-0.4.2-dev-eaa8b1ac-" "rows pdf-to-text Manual"
.SH NAME
rows\-pdf-to-text \- Extract text from a PDF
.SH SYNOPSIS
.B rows pdf-to-text
[OPTIONS] SOURCE [OUTPUT]
.SH DESCRIPTION
Extract text from a PDF
.SH OPTIONS
.TP
\fB\-i,\fP \-\-input\-option TEXT
Custom (import) plugin key=value custom option (can be specified multiple times)
.TP
\fB\-\-output\-encoding\fP TEXT
.PP
.TP
\fB\-q,\fP \-\-quiet
.PP
.TP
\fB\-\-backend\fP TEXT
.PP
.TP
\fB\-\-pages\fP TEXT
.PP
