.TH "ROWS CSV-MERGE" "1" "2020-12-16" "-0.4.2-dev-eaa8b1ac-" "rows csv-merge Manual"
.SH NAME
rows\-csv-merge \- Lazily merge CSVs (even if the schemas...
.SH SYNOPSIS
.B rows csv-merge
[OPTIONS] SOURCES... DESTINATION
.SH DESCRIPTION
Lazily merge CSVs (even if the schemas differs)
.SH OPTIONS
.TP
\fB\-\-input\-encoding\fP TEXT
.PP
.TP
\fB\-\-output\-encoding\fP TEXT
.PP
.TP
\fB\-\-no\-strip\fP
.PP
.TP
\fB\-\-no\-remove\-empty\-lines\fP
.PP
.TP
\fB\-\-sample\-size\fP INTEGER
.PP
.TP
\fB\-\-buffer\-size\fP INTEGER
.PP
