.TH "ROWS PGEXPORT" "1" "2020-12-16" "-0.4.2-dev-eaa8b1ac-" "rows pgexport Manual"
.SH NAME
rows\-pgexport \- Export a PostgreSQL table into a CSV file
.SH SYNOPSIS
.B rows pgexport
[OPTIONS] DATABASE_URI TABLE_NAME DESTINATION
.SH DESCRIPTION
Export a PostgreSQL table into a CSV file
.SH OPTIONS
.TP
\fB\-\-is\-query\fP
.PP
.TP
\fB\-\-output\-encoding\fP TEXT
.PP
.TP
\fB\-\-dialect\fP TEXT
.PP
