.TH "ROWS SQLITE-TO-CSV" "1" "2020-12-16" "-0.4.2-dev-eaa8b1ac-" "rows sqlite-to-csv Manual"
.SH NAME
rows\-sqlite-to-csv \- Convert a SQLite table into CSV
.SH SYNOPSIS
.B rows sqlite-to-csv
[OPTIONS] SOURCE TABLE_NAME OUTPUT
.SH DESCRIPTION
Convert a SQLite table into CSV
.SH OPTIONS
.TP
\fB\-\-batch\-size\fP INTEGER
.PP
.TP
\fB\-\-dialect\fP TEXT
.PP
