[pytest]
python_files =
    tests.py
    test_*.py
    tests_*.py
    *_tests.py
pythonpath = .
testpaths =
    tests
    rows
addopts =
    --doctest-modules
    --ignore-glob=data/
    --ignore-glob=docker/
    --ignore=examples/
    --ignore=rows/plugins/__init__.py
    --ignore=to-do/
    -vvvs
