[pytest]
python_files = tests.py test_*.py tests_*.py *_tests.py
pythonpath = .
testpaths =
    tests
    rows
addopts =
    --doctest-modules
    --ignore=to-do/
    --ignore=examples/
    --ignore=rows/plugins/__init__.py
    -vvvs
