.TH "ROWS PG2PG" "1" "2025-04-14" "0.5.0.dev0" "rows pg2pg Manual"
.SH NAME
rows\-pg2pg \- Copy data from one PostgreSQL instance to...
.SH SYNOPSIS
.B rows pg2pg
[OPTIONS] DATABASE_URI_FROM TABLE_NAME_OR_QUERY_FROM DATABASE_URI_TO TABLE_NAME_TO
.SH DESCRIPTION
Copy data from one PostgreSQL instance to another
.SH OPTIONS
.TP
\fB\-b,\fP \-\-binary
.PP
.TP
\fB\-\-chunk\-size\fP INTEGER
.PP
.TP
\fB\-e,\fP \-\-encoding TEXT
.PP
.TP
\fB\-\-no\-create\-table\fP
.PP
