.TH "ROWS CSV-ROW-COUNT" "1" "2025-04-14" "0.5.0.dev0" "rows csv-row-count Manual"
.SH NAME
rows\-csv-row-count \- Lazily count CSV rows
.SH SYNOPSIS
.B rows csv-row-count
[OPTIONS] SOURCE
.SH DESCRIPTION
Lazily count CSV rows
.SH OPTIONS
.TP
\fB\-\-input\-encoding\fP TEXT
.PP
.TP
\fB\-\-buffer\-size\fP INTEGER
.PP
.TP
\fB\-\-dialect\fP TEXT
.PP
.TP
\fB\-\-sample\-size\fP INTEGER
.PP
