.TH "ROWS CSV-INSPECT" "1" "2025-04-14" "0.5.0.dev0" "rows csv-inspect Manual"
.SH NAME
rows\-csv-inspect \- Identifies encoding, dialect and schema
.SH SYNOPSIS
.B rows csv-inspect
[OPTIONS] SOURCE
.SH DESCRIPTION
Identifies encoding, dialect and schema
.SH OPTIONS
.TP
\fB\-\-encoding\fP TEXT
.PP
.TP
\fB\-\-dialect\fP TEXT
.PP
.TP
\fB\-\-samples\fP INTEGER
Number of rows to determine the field types (0 = all)
