.TH "ROWS SQLITE-TO-CSV" "1" "2025-04-14" "0.5.0.dev0" "rows sqlite-to-csv Manual"
.SH NAME
rows\-sqlite-to-csv \- Convert a SQLite table into CSV
.SH SYNOPSIS
.B rows sqlite-to-csv
[OPTIONS] SOURCE TABLE_NAME OUTPUT
.SH DESCRIPTION
Convert a SQLite table into CSV
.SH OPTIONS
.TP
\fB\-\-batch\-size\fP INTEGER
.PP
.TP
\fB\-\-dialect\fP TEXT
.PP
