.TH "ROWS PGEXPORT" "1" "2025-04-14" "0.5.0.dev0" "rows pgexport Manual"
.SH NAME
rows\-pgexport \- Export a PostgreSQL table into a CSV file
.SH SYNOPSIS
.B rows pgexport
[OPTIONS] DATABASE_URI TABLE_NAME DESTINATION
.SH DESCRIPTION
Export a PostgreSQL table into a CSV file
.SH OPTIONS
.TP
\fB\-q,\fP \-\-is\-query
.PP
.TP
\fB\-e,\fP \-\-output\-encoding TEXT
.PP
.TP
\fB\-d,\fP \-\-dialect TEXT
.PP
