.TH "ROWS CSV-FIX" "1" "2025-04-14" "0.5.0.dev0" "rows csv-fix Manual"
.SH NAME
rows\-csv-fix \- Read a CSV file, merge down rows (if...
.SH SYNOPSIS
.B rows csv-fix
[OPTIONS] INPUT_FILENAME OUTPUT_FILENAME
.SH DESCRIPTION
Read a CSV file, merge down rows (if number of cols differ) and fix quotes
.SH OPTIONS
.TP
\fB\-\-log\-filename\fP TEXT
.PP
.TP
\fB\-\-log\-level\fP [NONE|CRITICAL|DEBUG|ERROR|FATAL|INFO|WARNING]
.PP
.TP
\fB\-\-input\-dialect\fP TEXT
.PP
.TP
\fB\-\-input\-encoding\fP TEXT
.PP
.TP
\fB\-\-output\-encoding\fP TEXT
.PP
.TP
\fB\-\-output\-dialect\fP TEXT
.PP
